spring:
  application:
    name: eureka-feign-client
server: 
  port:
    8092
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone:
        http://localhost:8088/eureka/
feign:
  hystrix:
    enabled:true
